;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
<<<<<<< HEAD
	isearch-exit
	org-self-insert-command
=======
	backward-delete-char
	kill-sexp
	org-self-insert-command
	paredit-forward-kill-word
>>>>>>> FETCH_HEAD
	))

(setq mc/cmds-to-run-once
      '(
<<<<<<< HEAD
	ido-switch-buffer
	isearch-forward-symbol-at-point
=======
>>>>>>> FETCH_HEAD
	))
