;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	<<<<<<<
	=======
	>>>>>>>
	FETCH_HEAD
	HEAD
	backward-delete-char
	isearch-exit
	kill-sexp
	org-self-insert-command
	org-self-insert-command
	paredit-forward-kill-word
	wdired-downcase-word
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	<<<<<<<
	=======
	>>>>>>>
	FETCH_HEAD
	HEAD
	ido-switch-buffer
	isearch-forward-symbol-at-point
	))
